### ISSUE TITLE
Getting "Can't pull image"

### ISSUE THREAD

**Issue by deejanu** [optiopay/klar#1]
We installed klar but unable to run it successfully. We have local ubuntu image that we wanted to scan. Our clair is running on Docker container (172.17.0.3). We tried following:

CLAIR_ADDR=http://172.17.0.3:6060 CLAIR_THRESHOLD=1 klar ubuntu:latest

and received following:
Can't pull image: Token request returned 401

We also tried to scan public image:
klar ubuntu:latest
and received the same error: Can't pull image: Token request returned 401

Are we missing some config parameters or env variables?
How would we run klar to scan images in public and/or private registry?

**Comment by hashmap** [comment]
Thanks for giving a try and reporting an issue you have. 
In the beginning you mentioned a local ubuntu image. Klar is supposed to be used with Docker registry, piblic or private. If you need to check a local image Clair itself provides a tool for that, perhaps in `contrib` folder. 
Answering your last 2 questions - try to add `DOCKER_USER` and `DOCKER_PASSWORD` with your actual Docker public registry credentials, `401` is a docker registry response, it seems it doesn't allow anonymous access via API. 
You can find an example of public image (postgres) check in readme file.

**Comment by hashmap** [comment]
Since there are no updates I'm closing this issue
