### ISSUE TITLE
Filter out unstable Debian issues

### ISSUE THREAD

**Issue by chrisfelix82** [optiopay/klar#10]
A lot of errors are unfixable because the fixes are in unreleased versions of Debian. Please allow filtering out of those results. Thanks.

**Comment by hashmap** [comment]
To be on the same page - do you want to filter out some vulnerabilities because fixes are not (and will not be for example) available for your distro? Would it just gives a false sense of security?

**Comment by chrisfelix82** [comment]
So the Debian distro is the only one that reports on unstable releases. So say I want to filter out those because I can't do an upgrade on the image to a non released version.

**Comment by chrisfelix82** [comment]
It can of course be made configurable. I just don't want the CI pipeline to fail because of it.

**Comment by hashmap** [comment]
@chrisfelix82 https://github.com/optiopay/klar/pull/98 brings this functionality, please try `2.1` release
