### ISSUE TITLE
feature name is missing from json output

### ISSUE THREAD

**Issue by jcodybaker** [optiopay/klar#103]
The feature name is missing from JSON output.  

It looks like the featureVersion has the wrong JSON tag and is masking it.

https://github.com/optiopay/klar/blob/ae9dbba8e0b5fbf85e9f86e0d8f6ba72f92bcd11/clair/clair.go#L57

My employer has a lengthly legal process for clearing open source code contributions.  I can start that process, but it could be some time until I'm able to offer a PR.  My apologies.

**Comment by jcodybaker** [comment]
@thereverendtom - It looks like this regressed in #98

**Comment by hashmap** [comment]
@jcodybaker thanks for the report and triage! I feel your pain, I worked for a big corp in the past:)
