### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by leoblanc** [optiopay/klar#11]
Hi, first of all congratulations for your work.

I have tried to create the Docker image of Klar using the latest Dockerfile.

This is the result:

```
Sending build context to Docker daemon 1.123 MB
Step 1 : FROM scratch
 ---> 
Step 2 : ENV DOMAIN skydns.local
 ---> Using cache
 ---> bd6f5e0205fc
Step 3 : ENV RELEASE 0.1
 ---> Using cache
 ---> f95d6f8a50b4
Step 4 : ENV ZONE_INFO /zoneinfo.zip
 ---> Using cache
 ---> 1cbaffced8a0
Step 5 : COPY assets/zoneinfo.zip /
 ---> Using cache
 ---> a7c974a97a0d
Step 6 : COPY assets/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
 ---> Using cache
 ---> a5ed1769c440
Step 7 : COPY klar /
lstat klar: no such file or directory
```

I have changed "klar" with "clair" (since no directory named klar exists) and it compile but can't start due a missing file too.

Can you please confirm if the current Dockerfile is able to build using "sudo docker build -t klar ." ?

Thank you very much in advance!

**Comment by leoblanc** [comment]
Oh, sorry, I just noted that I must build the Klar binary first, it's not included or pulled on the Dockerfile. Thank you!

**Comment by hashmap** [comment]
Please make sure you build a Linux binary. If you are on Mac or Wundows machine: `GOOS=linux go build .`
