### ISSUE TITLE
Header Authorization for request to clair: No token is set

### ISSUE THREAD

**Issue by savujevi** [optiopay/klar#12]
Hello developers,

if i use klaras desrcibed:

`CLAIR_ADDR=http://localhost CLAIR_THRESHOLD=10 DOCKER_USER=me DOCKER_PASSWORD=secret klar postgres:9.5.1`

with user and password these parameters are sue to get the dockerImages.
But if each layer is analyzed by clair it usese the token which is never initialized.

I have set the token in the docker.go by

`if i.Token == "" {
		req.SetBasicAuth(i.user, i.password)
		i.Token = req.Header.Get("Authorization")
	}`

Did i use the klar wrong or is there an other way to call klar ?

Thank you for your help.

Greatings
      Sascha

**Comment by hashmap** [comment]
Hello Sascha, thanks for the report. What error did you get exactly?

**Comment by hashmap** [comment]
@savujevi thanks for your fix, I submitted  it as a PR and merged it

**Comment by savujevi** [comment]
Thank you for the fix.
