### ISSUE TITLE
Prettify non-json output 

### ISSUE THREAD

**Issue by nabadger** [optiopay/klar#125]
Could potentially make use of something like https://github.com/olekukonko/tablewriter

It would be nice to have the following:

- A table format to show clear separation of fields
- A colour scheme in place to highlight vulnerabilities that fall in the *High* category or above.

This is mostly to make output easier to read, it may not add much real value since I suspect the exit-status is more important (and/or processing of the json output).

I wouldn't mind contributing to this project and taking this on if you think it's a nice idea?

**Comment by hashmap** [comment]
@nabadger sounds like a good idea!

**Comment by nabadger** [comment]
Let me know if the above PR is ok or if you have any suggestions.

Thanks :)

**Comment by nabadger** [comment]
This is now avail. in release v2.4.0 (can close this)
