### ISSUE TITLE
Can't pull image: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by gabrielfsousa** [optiopay/klar#140]
error using docker.io

"Can't pull image: invalid character '<' looking for beginning of value"

**Comment by hashmap** [comment]
Please provide more information, feel free to reopen, closing for now

**Comment by TriplEight** [comment]
Hello,
I had to switch to `buildah` to build images with GitlabCI and now I have this error.
https://gitlab.parity.io/parity/infrastructure/scripts/-/jobs/749573
