### ISSUE TITLE
Fails to analyze using API v3: grpc: failed to unmarshal the received message proto: bad wiretype for field clairpb

### ISSUE THREAD

**Issue by ethicalmohit** [optiopay/klar#150]
I am getting below error. I am not sure if its a bug or I am missing something.

clair mohit$ CLAIR_ADDR=http://localhost:6060 CLAIR_OUTPUT=Low CLAIR_THRESHOLD=10 klar nginx
clair timeout 1m0s
docker timeout: 1m0s
no whitelist file
Analysing 3 layers
Failed to analyze using API v1: push image https://registry-1.docker.io/v2/library/nginx:latest to Clair failed: can't even read an error message: invalid character 'N' looking for beginning of value

Failed to analyze using API v3: analyse image https://registry-1.docker.io/v2/library/nginx:latest failed: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: bad wiretype for field clairpb.Feature.Version: got wiretype 0, want 2

Failed to analyze, exiting

**Comment by tanushree-agilicus** [comment]
@ethicalmohit change your clair image to refer to clair: v2.08, not latest

**Comment by aaf1** [comment]
i have the same error for v3 api  
failed: rpc error: code = Internal desc = grpc: failed to unmarshal the received message proto: bad wiretype for field clairpb.Feature.Version: got wiretype 0, want 2

**Comment by ethicalmohit** [comment]
> @ethicalmohit change your clair image to refer to clair: v2.08, not latest

It worked with this image version: `quay.io/coreos/clair:v2.0.8`.
