### ISSUE TITLE
Recommended clair and klar versions ?

### ISSUE THREAD

**Issue by rodriguezsergio** [optiopay/klar#155]
This is mentioned in the release text for 2.4.0

> API V3 support seems to be broken by the latest Clair's master, we will try to update our code.

I'm currently running clair v2.0.9 and klar 2.4.0. Is there a better pairing that I should be looking at?

https://github.com/optiopay/klar/issues/110 suggests Clair 2.0.3 and Klar 2.3.0
but https://github.com/optiopay/klar/issues/127 suggests downgrading to Clair 2.0.0.

The reason I'm asking is because I'm seeing intermittent issues after I push to AWS ECR.

```
Failed to analyze using API v1: push image https://$IMAGE to Clair failed: can't even read an error message: unexpected end of JSON input

Failed to analyze using API v3: push image https://$IMAGE to Clair failed: rpc error: code = Unavailable desc = transport is closing

Failed to analyze, exiting
```

I will do some digging sometime during the week, but some recommendations would be much appreciated.

**Comment by zingyb** [comment]
@rodriguezsergio Were you able to determine anything?

**Comment by rodriguezsergio** [comment]
@zingyb I did not. $JOB is moving in a different direction to scan our Docker images.
