### ISSUE TITLE
json output

### ISSUE THREAD

**Issue by anonymez** [optiopay/klar#16]
Since in clair.go the function analyse returns a json, I would like to ask if it is possible to extend main.go from line 60 to 67 in order to let the user decide if she wants a json output or a human readable text.

A json output will integrate klar in many solutions since the results can be showed in any fashion you like.

**Comment by hashmap** [comment]
Initially Klar was designed with a clear and narrow goal - to be used in CI pipelines. However, I think it makes sense now to broaden the scope and support different use cases, e.g. use Klar output in a custom UI for image registry. Thanks for suggestion.
