### ISSUE TITLE
Can't pull fsLayers Error on 1.3

### ISSUE THREAD

**Issue by masoman22** [optiopay/klar#22]
After upgrading to 1.3 I'm getting "Can't pull fsLayers" error on some images

1.2.1 works fine for these same images. 

What information do you need from me?

/opt/klar-1.2.1 <ecr registry / image >
Analysing 28 layers
Found 11 vulnerabilities
...

/opt/klar-1.3 <ecr registry / image >
Can't pull fsLayers

**Comment by supereagle** [comment]
Maybe this is caused by PR #21

**Comment by furuholm** [comment]
I think you may be right. I have opened a separate issue for this: #27.

**Comment by hashmap** [comment]
@masoman22 could you test such images with 1.4? Meanwhile, I close the issue, will reopen it for 1.4 if needed. Thanks!
