### ISSUE TITLE
Possible to scan more than one image at a time?

### ISSUE THREAD

**Issue by mylespollie** [optiopay/klar#25]
Is Klar able to scan all images in my EC2 Repository at once? Or does each image have to be scanned individually?

**Comment by supereagle** [comment]
Now it only supports scanning images individually.

**Comment by dgellow** [comment]
@supereagle I'm curious about that. Is it a limitation from Klar or from Clair?

**Comment by supereagle** [comment]
@dgellow  It is a limitation from Klar. You can refer to the [usage](https://github.com/optiopay/klar#usage), the users have to specify the image to scan in the command line.

**Comment by mylespollie** [comment]
Anyone have any ideas for how to accomplish this with Clair?

**Comment by supereagle** [comment]
Maybe you need to write some code. First get list all images from Docker registry and then scan them one by one.
