### ISSUE TITLE
Support for image digest

### ISSUE THREAD

**Issue by jpprins1** [optiopay/klar#33]
Is it possible to also support image digests? Possible like:

    klar postgres@sha256:1364924c753d5ff7e2260cd34dc4ba05ebd40ee8193391220be0f9901d4e1651

(should be the same as postgres:9.6)

This would help testing specific running images in Docker/Kubernetes, for example if XXXX:latest is used or the tag is reused for a newer image, the version from the registry could be updated/not affected but your running image version is affected.

**Comment by supereagle** [comment]
This feature has been implemented by @furuholm in PR #28. Thanks @furuholm .

**Comment by hashmap** [comment]
Released as part of v1.4
