### ISSUE TITLE
Severity threshold

### ISSUE THREAD

**Issue by gauthier-delacroix** [optiopay/klar#41]
Klar currently allows to filter output by severity and has a threshold by high severity vulnerabilities count.

It would be nice to allow the customization of the threshold level, for example to include Medium vulnerabilities in the threshold count, and return 1 if any.

**Comment by supereagle** [comment]
If the severity level threshold is set to filter output, all the vulnerabilities outputted are cared by users. I think these outputted vulnerabilities could be counted, and return 1 if the number is larger then the threshold count.

@gauthier-delacroix @hashmap   Any comments about this design? If you think it is ok, I can submit a PR for this.

**Comment by hashmap** [comment]
@supereagle sounds good to me
