### ISSUE TITLE
Scan GCR public container images

### ISSUE THREAD

**Issue by xueshanf** [optiopay/klar#42]
I am wondering how to scan public images hosted on GCR, e.g. gcr.io/google-containers/busybox. No authentication is needed in this case, but klar would give this error:

```
docker run --env-file=envs my-klar gcr.io/google-containers/busybox
Can't pull image: Can't parse Www-Authenticate: Basic realm=""
```
My envs contains no DOCKER_USER and DOCKER_PASSWORD:
```
CLAIR_ADDR=https://clair.example.com
```
Thanks!

**Comment by supereagle** [comment]
@hashmap  Could we update the GCR support like [Amazon ECR support](https://github.com/optiopay/klar#amazon-ecr-support) in README?

**Comment by hashmap** [comment]
@xueshanf thanks for reporting! It seems we introduced a regression - if DOCKER_USER is not specified Klar can't pull even public images

@supereagle it's not related to GCR, this is a bug

**Comment by hashmap** [comment]
@xueshanf please test version 1.4.1, it should be fixed

**Comment by xueshanf** [comment]
@hashmap Yup! It's fixed. Thanks for fast response. Great tool!

**Comment by supereagle** [comment]
@hashmap  Thanks for fixing.
