### ISSUE TITLE
Examples for citicality

### ISSUE THREAD

**Issue by wurstbrot** [optiopay/klar#48]
I am using clairctl, but the output is not as nice structured as klar. In clairctl, I get the overview of ciritcalities like this:
Unknown: x
 Negligible: x
 Low: x
 Medium: x
 High: x
 Critical: x
 Defcon1: x

I asume that klar useses the same ciriticalities? To integrate klar into my Jenkins with the logparser plugin, I need to know what to grep for.

**Comment by supereagle** [comment]
Yes, both klar and clairctl use the same criticality levels.

**Comment by hashmap** [comment]
> To integrate klar into my Jenkins with the logparser plugin, I need to know what to grep for.

This option may help:

> CLAIR_OUTPUT - severity level threshold, vulnerabilities with severity level higher than or equal to this threshold will be outputted. Supported levels are Unknown, Negligible, Low, Medium, High, Critical, Defcon1. Default is Unknown

**Comment by wurstbrot** [comment]
Thank you! I am blind ...
