### ISSUE TITLE
cannot build code with go in linux

### ISSUE THREAD

**Issue by umanam** [optiopay/klar#50]
Cannot build code with go in linux environment.

 go build .
main.go:10:2: cannot find package "github.com/optiopay/klar/clair" in any of:
	/usr/local/go/src/github.com/optiopay/klar/clair (from $GOROOT)
	/root/go/src/github.com/optiopay/klar/clair (from $GOPATH)
main.go:11:2: cannot find package "github.com/optiopay/klar/docker" in any of:
	/usr/local/go/src/github.com/optiopay/klar/docker (from $GOROOT)
	/root/go/src/github.com/optiopay/klar/docker (from $GOPATH)

**Comment by hashmap** [comment]
Make sure that Klar source code is in `$GOPATH/src/github.com/optiopay/klar`
