### ISSUE TITLE
Support basic authentication

### ISSUE THREAD

**Issue by alexppg** [optiopay/klar#76]
It would be nice to support basic authentication, since the default behavior is to be open to everybody.

**Comment by hashmap** [comment]
@alexppg  Do you mean request to Clair, right?

**Comment by alexppg** [comment]
Yes. @hashmap

**Comment by Johannestegner** [comment]
This would really be great, or basically any type of auth for the Clair server, so that it can be exposed to the web. Is anyone working on this? :)

**Comment by qiq** [comment]
Just checked, basic auth works out-of-the-box in Klar (at least for v1 API):
```
CLAIR_ADDR=https://LOGIN:PASSWORD@HOST:PORT
```

To add basic authentication to Clair when using ingress-nginx, follow the official docs: https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/basic

**Comment by qiq** [comment]
Pull request with README update: https://github.com/optiopay/klar/pull/130

**Comment by alexppg** [comment]
I have not tried it, but since it's done a looot ago, I'll just open another issue if I need to. Thanks for your efforts!
