### ISSUE TITLE
Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by roxspring** [optiopay/klar#88]
I'm seeing the following an awful lot: `Failed to analyze using API v1: push image <nameofimage> to Clair failed: can't push layer to Clair: Post <clairurl>/v1/layers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Presumably because clair is initially empty and having to download all the layers afresh, therefore taking more than whatever default timeout is set. 

Is there a configuration option or preferably an environment variable I can use to increase the timeout?

**Comment by hashmap** [comment]
Yeah, let's extend the default timeout + add env var to control it. I will add it to upcoming 2.1.0 release.
